-- MySQL Script generated by MySQL Workbench
-- Mon Feb  3 13:17:04 2025
-- Model: New Model Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WA_projekt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WA_projekt`;
CREATE SCHEMA IF NOT EXISTS `WA_projekt`;
USE `WA_projekt`;

-- -----------------------------------------------------
-- Table `WA_projekt`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Users`;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Users` (
  `id` INT AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `unique_name` (`Name`)
);

-- -----------------------------------------------------
-- Table `WA_projekt`.`Meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Meals`;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Meals` (
  `id` INT AUTO_INCREMENT,
  `Name` VARCHAR(255),
  `Type` VARCHAR(255),
  `Description` VARCHAR(255),
  PRIMARY KEY (`id`)
);

-- -----------------------------------------------------
-- Table `WA_projekt`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Ratings`;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Ratings` (
  `id` INT AUTO_INCREMENT,
  `User_id` INT NOT NULL,
  `Portion_size` INT NOT NULL,
  CHECK (Portion_size >= 1 AND Portion_size <= 5),
  
  `Food_temperature` INT NOT NULL,
  CHECK (Food_temperature >= 1 AND Food_temperature <= 5),
  
  `Willing_to_pay` INT NOT NULL,
  CHECK (Willing_to_pay >= 1 AND Willing_to_pay <= 5),
  
  `Food_appearance` INT NOT NULL,
  CHECK (Food_appearance >= 1 AND Food_appearance <= 5),
  
  `Created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  
  PRIMARY KEY (`id`),
  INDEX `idx_user_id` (`User_id`),
  
  CONSTRAINT `fk_ratings_user`
    FOREIGN KEY (`User_id`)
    REFERENCES `WA_projekt`.`Users` (`id`)
);

-- -----------------------------------------------------
-- Table `WA_projekt`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Menu`;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Menu` (
  `id` INT AUTO_INCREMENT,
  `date` DATE,
  PRIMARY KEY (`id`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `WA_projekt`.`Item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Item`;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Item` (
  `id` INT AUTO_INCREMENT,
  `Meals_id` INT NOT NULL,
  `Menu_id` INT NOT NULL,
  `Ratings_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  
  INDEX `fk_item_Meals1_idx` (`Meals_id`),
  INDEX `fk_item_Menu1_idx` (`Menu_id`),
  INDEX `fk_item_Ratings1_idx` (`Ratings_id`),
  
  CONSTRAINT `fk_item_Meals1`
    FOREIGN KEY (`Meals_id`)
    REFERENCES `WA_projekt`.`Meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  
  CONSTRAINT `fk_item_Menu1`
    FOREIGN KEY (`Menu_id`)
    REFERENCES `WA_projekt`.`Menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  
  CONSTRAINT `fk_item_Ratings1`
    FOREIGN KEY (`Ratings_id`)
    REFERENCES `WA_projekt`.`Ratings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
