-- MySQL Script generated by MySQL Workbench
-- Sat Feb  1 17:39:46 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema WA_projekt
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `WA_projekt` ;

CREATE SCHEMA IF NOT EXISTS `WA_projekt` ;
USE `WA_projekt` ;

-- -----------------------------------------------------
-- Table `WA_projekt`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Users` ;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `role` ENUM('student', 'admin') NULL DEFAULT 'student',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX (`email` ASC));

-- -----------------------------------------------------
-- Table `WA_projekt`.`Meals`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Meals` ;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Meals` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `type` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`));

-- -----------------------------------------------------
-- Table `WA_projekt`.`Ratings`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`Ratings` ;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`Ratings` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `portion_size` ENUM('hlad', 'akorat', 'prejedl') NULL DEFAULT NULL,
  `food_temperature` ENUM('studene', 'akorat', 'horke') NULL DEFAULT NULL,
  `willing_to_pay` DECIMAL(5,2) NULL DEFAULT NULL,
  `food_appearance` ENUM('spatne', 'dobre', 'vyborne') NULL DEFAULT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  INDEX (`user_id` ASC),
  CONSTRAINT `fk_ratings_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `WA_projekt`.`Users` (`id`));

-- -----------------------------------------------------
-- Table `WA_projekt`.`menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`menu` ;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`menu` (
  `idmenu` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NULL,
  PRIMARY KEY (`idmenu`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `WA_projekt`.`item`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `WA_projekt`.`item` ;

CREATE TABLE IF NOT EXISTS `WA_projekt`.`item` (
  `iditem` INT NOT NULL AUTO_INCREMENT,
  `Meals_id` INT NOT NULL,
  `menu_idmenu` INT NOT NULL,
  `Ratings_id` INT NOT NULL,
  PRIMARY KEY (`iditem`),
  INDEX `fk_item_Meals1_idx` (`Meals_id` ASC),
  INDEX `fk_item_menu1_idx` (`menu_idmenu` ASC),
  INDEX `fk_item_Ratings1_idx` (`Ratings_id` ASC),
  CONSTRAINT `fk_item_Meals1`
    FOREIGN KEY (`Meals_id`)
    REFERENCES `WA_projekt`.`Meals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_menu1`
    FOREIGN KEY (`menu_idmenu`)
    REFERENCES `WA_projekt`.`menu` (`idmenu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_Ratings1`
    FOREIGN KEY (`Ratings_id`)
    REFERENCES `WA_projekt`.`Ratings` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- Insert sample data into Users
INSERT INTO `WA_projekt`.`Users` (`name`, `email`, `role`) VALUES
('Alice Johnson', 'alice@example.com', 'student'),
('Bob Smith', 'bob@example.com', 'admin'),
('Charlie Brown', 'charlie@example.com', 'student');

-- Insert sample data into Meals
INSERT INTO `WA_projekt`.`Meals` (`name`, `type`, `description`) VALUES
('Spaghetti Bolognese', 'Main Course', 'Pasta with meat sauce'),
('Caesar Salad', 'Appetizer', 'Salad with romaine lettuce and Caesar dressing'),
('Chocolate Cake', 'Dessert', 'Rich chocolate layered cake');

-- Insert sample data into Ratings
INSERT INTO `WA_projekt`.`Ratings` (`user_id`, `portion_size`, `food_temperature`, `willing_to_pay`, `food_appearance`) VALUES
(1, 'akorat', 'horke', 12.50, 'vyborne'),
(2, 'prejedl', 'akorat', 15.00, 'dobre'),
(3, 'hlad', 'studene', 8.75, 'spatne');

-- Insert sample data into menu
INSERT INTO `WA_projekt`.`menu` (`idmenu`, `date`) VALUES
(1, '2025-02-01'),
(2, '2025-02-02'),
(3, '2025-02-03');

-- Insert sample data into item
INSERT INTO `WA_projekt`.`item` (`iditem`, `Meals_id`, `menu_idmenu`, `Ratings_id`) VALUES
(1, 1, 1, 1),
(2, 2, 1, 2),
(3, 3, 2, 3);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
